Documents/Oisin_Workspace/.$SystemArchitecture.drawio.dtmp
Documents/Oisin_Workspace/SystemArchitecture.drawio

// Describe what you have changed/added/removed in the pull request. 
// Describe the reason for the pull request. What feature is it adding/working towards?
// (Optional) Include a demo recording of changes working.

System Architecture

---

D22124271.md

Created a D22124271 MD file with hello world and basic student information.
I have added a .md file to repository with my student number
It was the first homework task for Github

Created MD file for first commit

---

D22124341.md

created homework file saved with student id
Created a file with Hello World saved as a .md file. 
To complete a homework task

Created md file for homework

---

Documents/nishant_research/Node vs Springboot.txt

Published a research text based file where we have info about the pros and cons of both approaches.
Tried looking for drawbacks and benefits of nodeVs Springboot
We needed to know which is the best approach for the Group project.

Research of Node vs SpringBoot

---

.gitattributes
Datasets/Part_1_Crime_Data--_Legacy_Data_(Discontinued_Date_7_22_2023).csv

Created a dataset folder that will contain all datasets in the project
For everyone to access, to be able to pull datasets directly from github when working with code

added dataset file

---

Datasets/BPD_Arrests.csv
Datasets/CCTV_Locations_Cameras.csv
Documents/nishant_research/AWSaccounts.txt

Added Datasets into project
More data for the project

Added other datasets

---

Documents/Stephen_Workspace/Baltimore EPA.ipynb

Created a dataframe to store crimes per neighborhood
// Created a new dataframe with just neigborhoods and the average frequency of each crime recorded
// Sean requested for this table to help merge with his dataset

Added Neigbourhood specific crime data

---

Datasets/appartment_building_information.csv
Datasets/individual_unit_information.csv
Datasets/property_data_extended.csv

These datasets are the new datasets as described in my last commit, they contain new information and have been strategical separated to be integrated into a schema, 
We did this as now further insights can now be made through EDA, and tables can now be linked to crime datasets with newly provided addresses

Uploaded three datasets

---

Documents/Stephen_Workspace/Baltimore_businesses.ipynb

I am using the Google Places API to pull restaurants in Baltimore, which is the first of other business types i will be extracting details on.
I have created a dataset for restaurants in Baltimore using Google Places dataset 
So that we can use this information to tell which businesses are close to which rent properties we will be displaying

Pulling Baltimore businesses dataset

---

Datasets/apartment_building_information.csv
Datasets/apartment_unit_information.csv
Datasets/image_data.csv
Datasets/propertyExtendedSearch.csv

I have enhanced the datasets by incorporating geolocation features. Additionally, I've extracted all image URLs for each property, making them readily available for display. Furthermore, I've standardized the image width to 960 pixels for every image."
The data team can utilize these tables to commence the schema development process and establish relationships between them. The key attributes for linking the tables would ideally be geolocation for building information, address for crime data, zpid for individual property information, and lotID for specialized information pertaining to the 12 key properties' buildings.

Added new and updated datasets

---

911_calls_for_service.csv
Part_1_Crime_Data--_Legacy_Data_(Discontinued_Date_7_22_2023).csv
addresses.csv
all_fees.csv
all_property_keys.csv
apartment_building_information.csv
apartment_unit_information.csv
exterior_features.csv
image_data.csv
image_data_all.csv
indoor_features.csv
interior_features.csv
main_information.csv
nearby_schools.csv
price_history.csv
propertyExtendedSearch.csv
property_keys_non_units.csv
property_keys_units.csv
quick_glance_features.csv
walk_scores.csv

These datasets contain all the information we need to build a schema for the 820 properties we have

Uploading 16 datasets

---

Documents/nishant_research/Linking Data.txt
Documents/nishant_research/Spatial Data Types.txt

added information about linking data, and sample queries for AWS.
Tried sample queries on Amazon Aurora to get familiar in local AWS (external to project
)
Familiarity with AWS environment and DB,

added information about linking data, and sample queries for AWS.

---

retrospective.md

Created retrospective md for team members to add in their weekly lessons learnt, what went well and what could be improved.
Introduced a structured format for conducting team retrospectives.
Defined sections for capturing what went well, areas of improvement, and action items.
Included placeholders for team members to provide individual feedback.
To standardize the way our team conducts retrospectives.
To ensure that feedback from all team members is captured systematically.
To facilitate more productive and organized retrospective sessions in the future.

Created a retrospective.md

---

Documents/Stephen_Workspace/Baltimore_businesses.ipynb

I experimented with pulling the details for multiple businesses and tried a reverse coordinate search for neighborhoods
Updated the code to pull details of multiple businesses. 
To get help build a dataset of businesses around properties

Testing pulling of multiple business details

---

Documents/Stephen_Workspace/Baltimore_businesses.ipynb

I listed a number of neighborhoods and made a request for business type "restaurant" for all these neighborhoods 
This is so we can have the properties in a particular neighborhoods find the businesses that are around them

Testing pulling business data for neigbourhoods

---

DatasetDocumentation.md
Documents/nishant_research/Normalized Tables for Addresses.txt

Added dataset documentation for data team to add.
Moved database to 
Github space reduction was needed.

Created dataset documentation

---

Documents/Stephen_Workspace/Baltimore_businesses.ipynb

I used the neighborhood location details as a parameter to search for all restaurants nearby those neighborhoods
So that we can have the restaurants in a neighborhood and the distance from the center point of those neighborhoods

Getting restaurants for all the neigborhoods

---

retrospective.md

Everyone got on a call and shared their retrospective.
As the PM. For this week I wrote all the feedback to a md document.

Updated Retrospective.md

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

I am testing out extracting data with only allowed columns
This is to adhere to the Google Places policy

Extracting details ensuring Google cache policy

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

Extracted bar location data around the neighborhoods
To have the location data of all the bars nearby

Updated Baltimore businesses with bar data

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

Extracted location data for beauty salons
To have location data on beauty salons for our dataset

Updated Baltimore businesses with beauty salon

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

I extracted location data for police around the neighborhood
To have police locations present in the neighborhood for our database

Updated baltimore businesses with police location data

---

frontend/src/MockData/PropertyDataSample.js
frontend/src/components/Carousel/Carousel.js
frontend/src/components/CommonComp/Cards/PropertyCard/PropertyCard.js

-Created Carousel for property images.
-modified propertyDataSample -> images in an array.
-modified the propertyCard to show first image of the array only.
Working toward the property detail page. 
https://github.com/oisintheginger/mscfinalproject/assets/105603600/6338b996-120c-4fcc-b475-5f155a169ccd

Modding mockdata for carousel

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

I tried out a function to filter out just the location coordinates from the geometry column
the geometry column had values for the bounding box for the places that we are not going to need so I did this to remove them

Filtering Location coordinates

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

Trying out the function on another business location data
Filtering the geometry column and checking the CSV file created to inspect changes

Filtering Location coordinates for art galleries

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

I removed the bounding box coordinates from the bank location data
To have filtered location data for banks

Filtering bank location data

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

Formatted the location data for bars
So that we have the right location data format for the bars dataset

filtered bar location data

---

Documents/Stephen_Workspace/Baltimore_businesses_2.ipynb

I formatted the location data of multiple business datasets
To format the location data for the rest of the businesses

formatting businesses

---

retrospective.md

Updated the retrospective file with our comments
To have comments for our week 6 retrospective

Updating retrospective

---

Documents/Backend_documentation/Cogito userid and authorisation token retrieval.md

added documentation for how to use retrieve data from cognito user pool that we need 
We need cognito user pool user id's and authorisation tokens to implement authorisation on the backend and create a user table to save saved searches, favourite properties and user preferences

Cognito authorisation research 

---

frontend/src/Pages/PropertyPage.js
frontend/src/components/CreateApplicationModal/ApplyModal.js
frontend/src/components/SearchAndFilters/RenderSaveSearch.js

-Application modal now has a form to fill out.
-My Saved Searches now looking closer to figma
-The users need to be able to apply for properties to rent
-The Saved Search Page needed a bit of sprucing up
https://github.com/oisintheginger/mscfinalproject/assets/105603600/b492135f-95fd-4c60-a182-e1cddba88304

ApplicationForm

---

frontend/src/components/CommonComp/Cards/PropertyCard/PropertyCard.js
frontend/src/components/MapComponent/LeafletMap.js

- removed the double card effect on the map popups.
It looked ugly, so we had to fix that.
N/A

Fix map popups

---

frontend/src/Pages/PageTemplate.js

Put in placeholder information for footer 
More cohesive and professional look on the website.
N/A

Fix footer

---

Documents/Oisin_Workspace/MScVault/.obsidian/workspace.json
Documents/Oisin_Workspace/MScVault/Daily Diary/1st November 2023.md
Documents/Oisin_Workspace/MScVault/Daily Diary/2nd November 2023.md
Documents/Oisin_Workspace/MScVault/Daily Diary/Tuesday 31st October.md
frontend/src/index.js

I was able to set up a test lambda function and a test API gateway. By doing this I was able to understand the process for connecting to the backend. Unfortunately, there is a blocker to continuiing until CORS is enabled on the backend, but once that issue is sorted, it should prove more straightforward to connect to the backend.
- Created a Test API on API Gateway
- Created a test Lambda Function on AWS
- Connected to the test function from Frontend using Amplify API library

Setup a Test with API Gateway and Amplify

---

frontend/src/App.css
frontend/src/Pages/BreadCrumbMapper.js
frontend/src/Pages/ContactInformation.js
frontend/src/Pages/Homepage.js
frontend/src/Pages/PageTemplate.js
frontend/src/Pages/PrivacyPolicy.js
frontend/src/Pages/TermsAndConditionsPage.js
frontend/src/Routers/HMERouter.js
frontend/src/components/SiteFooter/SiteFooter.js

We added the misclenneous documents pages for the Privacy Notice and Terms and Conditions. These are just placeholders because obviously I amn't a lawyer. I copied most of them from template and added them to the pages. 
I also set up routing to and from these pages.
Also, refactored the footer into its own component.
Don't want to get us sued lol

Create misc document page

---

.idea/workspace.xml
Backend/.idea/dataSources.xml
Backend/pom.xml
Backend/src/main/java/msc/HME/JpaConfig.java
Backend/src/main/java/msc/HME/controller/PropertiesController.java
Backend/src/main/resources/application.properties
Documents/Fenna_Workspace/DbConnectionHell.md

- added necessary configuration in application.properties and JpaConfig java class to connect to the rds instance
- added documentation of the complicated process of trying to connect 
cuz its absolutely necessary lol

DB connection 

---

Documents/Oisin_Workspace/MScVault/.obsidian/workspace.json
frontend/package-lock.json
frontend/package.json
frontend/src/Pages/Browse.js
frontend/src/Pages/Profile.js
frontend/src/Pages/PropertyPage.js
frontend/src/Styling/theme.js
frontend/src/components/Carousel/Carousel.js
frontend/src/components/CommonComp/Cards/PropertyCard/PropertyCard.js
frontend/src/components/MapComponent/PropertyDetailMap.js
frontend/src/components/UserWeightsComponent/UserWeights.js
frontend/src/index.js

- Created the Component for the user to adjust their recommendation weights
- Updated the code on the property detail page to reflect the backend response keys
- Adjusted the image carousel to look better with the new data
Needed to be done man
https://github.com/oisintheginger/mscfinalproject/assets/32101314/651bad7f-2842-452d-9131-456ba7d43806

User Weights Component + Fixing Property Details Page

---

Documents/Stephen_Workspace/neighborhood_coordinates.ipynb

Extracting the neighborhood names and coordinates as they show on Google maps
So the neighborhood details from the crime dataset match that of the property dataset

Extracting neighborhood coordinates-work from last week with Sean

---

Documents/Stephen_Workspace/Tagging System Notes.md

Updating Tagging system notes

---

Documents/nishant_research/DatabaseCreation/KNN-OnCloud.txt
Documents/nishant_research/DatabaseCreation/Queries Itelration/QueriesBackEND.sql
Documents/nishant_research/scoringsystembarebones.py

Nishant research

---

Documents/nishant_research/DatabaseCreation/Queries Itelration/RecomenderSystem.txt
Documents/nishant_research/knnAttempt.ipynb

Prep of data for KNN

---

Backend/src/main/java/msc/HME/DatabaseConfig.java
Documents/Backend_documentation/swagger.yaml

- set db connection idle timeout 
- update backend docs

Connection fix + update documentation 

---

Backend/src/main/java/msc/HME/binding/UserWeights.java
Backend/src/main/java/msc/HME/mapper/UserRowMapper.java
Backend/src/main/java/msc/HME/mapper/UserWeightsRowMapper.java

small fixes for user endpoint because of cognito trigger changes

Update binding and mappers

---

Documents/Stephen_Workspace/handler.py

Updating the file with configuration values
To allow connection to the database to create tags

Creating handler file

---

Documents/Stephen_Workspace/handler.py

Testing handler by querying BusStations table
To see if I am able to make queries

Testing handler

---

Backend/src/main/java/msc/HME/DatabaseConfig.java
Backend/src/main/java/msc/HME/binding/DetailedProperty.java
Backend/src/main/java/msc/HME/service/PropertyService.java
Backend/src/main/java/msc/HME/service/UserService.java

small refactorings had to be done
- the property details endpoint returns the services counts now
- bug in JWT validation
- clean up db configurations

Refactoring REST API

---

Documents/Stephen_Workspace/handler.py

Comparing the values in the columns of the rows
Trying out code to create the tag

Updating the handler file

---

Backend/pom.xml
Backend/src/test/java/msc/HME/StreamLambdaHandlerTest.java
Backend/src/test/java/msc/HME/controller/PropertiesControllerTest.java

small debugging and refactoring

Fenna Development

---

Documents/Stephen_Workspace/handler.py

Adding code to display the top three services 
To show which services are dominant in that neighbourhood

Updating the handler script

---

Documents/Stephen_Workspace/handler.py

Using the handler script to check on the safe area tags for the neighbourhoods 
To show what neighbourhoods are tagged as safe areas

Updating handler file for safety tags

---

frontend/src/Pages/Applications.js
frontend/src/Pages/Favorites.js
frontend/src/Utils/UserContext/UserContextProvider.js

- User's favorite properties displaying on my favorites
// Describe the reason for the pull request. What feature is it adding/working towards?
https://github.com/oisintheginger/mscfinalproject/assets/32101314/95f7123b-443c-4ede-8233-c5eae5855ea4

Favorites Page

---

Documents/Oisin_Workspace/MScVault/.obsidian/workspace.json
Documents/Oisin_Workspace/MScVault/Daily Diary/November/22nd November Wednesday.md
Documents/Oisin_Workspace/MScVault/Daily Diary/November/23rd November Thursday.md
frontend/src/Pages/Applications.js
frontend/src/Pages/PropertyPage.js
frontend/src/Utils/Mutations/ProfileMutation/ProfileMutation.js
frontend/src/components/UserWeightsComponent/UserWeights.js

- User Weights adjustment component now works
- Users needed to be able to adjust their score weights 
https://github.com/oisintheginger/mscfinalproject/assets/32101314/9498bbf8-10be-4da9-8b3b-80a9f7c1ce48

User Weights

---

Backend/src/main/java/msc/HME/controller/UserController.java
Backend/src/main/java/msc/HME/service/UserService.java

somehow left some commits out of my last user endpoint fix pr

Endpoint fix

---

frontend/src/components/SearchAndFilters/RenderSaveSearch.js

- get saved searches
- render them in table format (If empty render "No saved searches")
- delete search
- pagination
- onClick ButtonBase take me to search url -> can click anywhere to navigate to search, provided it's not the delete button.
- before reloading, will tell user that the deletion was successful
- added functionality
https://github.com/oisintheginger/mscfinalproject/assets/105603600/b4cbe389-7c4a-40a6-b518-c0969a5df223

Charlotte save search page

---

Documents/Oisin_Workspace/MScVault/.obsidian/workspace.json
Documents/Oisin_Workspace/MScVault/Daily Diary/November/23rd November Thursday.md
Documents/Oisin_Workspace/MScVault/Daily Diary/November/24th November Friday.md
frontend/src/Pages/Browse.js
frontend/src/Pages/PropertyPage.js
frontend/src/components/MapComponent/LeafletMap.js
frontend/src/components/MapComponent/MapBrowsing.js
frontend/src/components/MapPopup/MapPropertyPopup.js

- Added a new Modal for map quick-views
- Map results grid working now without causing DB crash
- Current Map popup wasn't mobile friendly
- Map browsing was causing DB crash through 1500 requests per second.
https://github.com/oisintheginger/mscfinalproject/assets/32101314/8c4cd40f-6d1f-46fb-bb85-d4c449799f9a

Fixing Map Browsing + Replacing Map Popups

---

Documents/Stephen_Workspace/handler.py

Defining a threshold for safety using the mapped z scores
So it can be used to decide on safe area tags

Updating handler script for safety tag

---

Documents/Stephen_Workspace/Tagging System.ipynb

Creating a new dataframe
to store all the tags in

creating tags table

---

Documents/Stephen_Workspace/Tagging System.ipynb

Formatting tags by renaming
So it is more presentable to users

formatting tags

---

Backend/src/main/java/msc/HME/controller/PropertiesController.java
Backend/src/main/java/msc/HME/service/PropertyService.java
Backend/src/main/java/msc/HME/service/UserService.java
Documents/Backend_documentation/swagger.yaml

added an endpoint to retain the user evaluations for the recommendation systems. Pr includes updated documentation.

User Recommendation Evaluation Endpoint

---

frontend/src/Pages/Applications.js
frontend/src/Pages/Browse.js
frontend/src/Pages/Favorites.js
frontend/src/Pages/PropertyPage.js
frontend/src/Pages/Youtube links/YouTubeVideo.js
frontend/src/Utils/DataFetching/FetchFavoritesHook.js
frontend/src/Utils/DataFetching/FetchPropertyDetailsHook.js
frontend/src/Utils/Mutations/FavoriteMutation/FavoritesMutation.js
frontend/src/Utils/Mutations/RecommendationMutation/RecommendationMutation.js
frontend/src/Utils/QueryConstants/QueryKeyConstants.js
frontend/src/components/CommonComp/Cards/PropertyCard/PropertyCard.js
frontend/src/components/CommonComp/Cards/RecommendationCard/RecommendationCard.js
frontend/src/components/CommonComp/PropertyTags/PropertyTags.js
frontend/src/components/MapComponent/PropertyDetailMap.js
frontend/src/components/ResultsGrid/ResultsGrid.js
frontend/src/components/SaveSearch/RenderSaveSearch.js

- Fix pagination issue on Saved Searches Page
- Added tags to the property card and property details page
- made the video element on the FAQ page responsive
- Recommendation Feedback now working on Recommendation Card
Thought it would be funny
https://youtu.be/k1nEN4WJBQg

Tags on property page + Miscellaneous Tweaks

---

sean/sean_sql/PropertySchemaCreation2.sql

Sql script updates, nothing major

Sean sql schema creation

---

Backend/src/main/java/msc/HME/service/PropertyService.java
cognitoTrigger/.idea/misc.xml
cognitoTrigger/pom.xml
cognitoTrigger/src/main/java/msc/HME/LambdaHandler.java

changes to resolve issues with cognito trigger today

cognito trigger

---

Documents/Oisin_Workspace/MScVault/.obsidian/workspace.json
Documents/Oisin_Workspace/MScVault/Daily Diary/December/2nd December Saturday.md
Documents/Oisin_Workspace/MScVault/Daily Diary/December/4th December Monday.md
frontend/src/Pages/Applications.js
frontend/src/Pages/Browse.js
frontend/src/Pages/Favorites.js
frontend/src/Pages/Homepage.js
frontend/src/Styling/theme.js
frontend/src/components/CommonComp/Cards/ApplicationCard/ApplicationCard.js
frontend/src/components/CommonComp/Cards/PropertyCard/PropertyCard.js
frontend/src/components/MapComponent/LeafletMap.js
frontend/src/components/MapComponent/MapToggleList.js
frontend/src/components/PropertyScoresComponent/PropertyScoresComponent.js
frontend/src/components/ResultsGrid/ResultsGrid.js
frontend/src/components/SaveSearch/RenderSaveSearch.js
frontend/src/components/SearchAndFilters/SearchAndFilter.js
frontend/src/components/SearchCard/SearchCard.js
frontend/src/components/UserWeightsComponent/UserWeights.js

Based on this evaluation: https://youtu.be/YR7dDrs88qg , I made some adjustments to the site.
Additionally:
- Added manual reorder buttons to the user weights component
- Modified the page change to scroll to the top of the results grid on browsing, map browsing etc.
Improving Site Accessibility
https://youtu.be/Zxpg3jpbSFs

Oisin Accessibility Evaluation Adjustments

---

retrospective.md

Updating the retro document with our comments

Updating retro document

---

frontend/src/Pages/FAQPage.js

Update FAQ video link

---

frontend/src/Pages/Browse.js
frontend/src/Styling/theme.js
frontend/src/components/ActiveTag/ActiveTagsStack.js
frontend/src/components/SearchAndFilters/SearchAndFilter.js
frontend/src/components/SearchCard/SearchCard.js

- Minor Styling Edits for Demo
// Describe the reason for the pull request. What feature is it adding/working towards?
// (Optional) Include a demo recording of changes working.

Final touch ups

---

sean/sean_lambda/HaversineFormulaIterations/handler.py

This code contains the first iteration of the code I wrote for this function that finds the 10 nearest properties to an inputted property. The final iteration of the code works. We didn't have time to implement the final function but it would be deployed in future work.

Code I wrote to find nearby properties when clicked

---

sean_notebooks/graphs for final report.ipynb

Code to make graphs used in final presentation

Create graphs for final report.ipynb
